server.port: 40010
spring:
  datasource:
    url: jdbc:mariadb://maria-db-1:3306/finance
    driverClassName: org.mariadb.jdbc.Driver
    username: OverideMe
    password: OverideMe
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
