server.port: 8080
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    url: jdbc:sqlite:local.db
    driverClassName: org.sqlite.JDBC
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect