server.port: 40010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ##OVERRIDE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
