server.port: 8080
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    url: jdbc:mariadb://localhost:3306/finance

    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect