server.port: 40010
spring:
  datasource:
    url: jdbc:sqlite:/local/db/finance.db
    driverClassName: org.sqlite.JDBC
#    username: root
#    password: ##OVERRIDE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
