server.port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://192.168.0.184:3306/finance
#    url: jdbc:h2:mem:testdb
    #spring.datasource.driverClassName: org.h2.Driver
    username: sa
    password: sa