server.port: 40010
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    #spring.datasource.driverClassName: org.h2.Driver
    username: root
    password: ##OVERRIDE
